// Canonical power names with curated aliases/variants. Keep entries concise and unambiguous.
export const POWER_ALIASES = {
  "Jeffrey Epstein": [
    "jeffrey epstein",
    "jeff epstein",
    "jeffrey e. epstein",
    "jeffrey e epstein",
    "jeffrey e.",
    "epstein",
    "jeffrey e. — financier",
    "jeffrey epstein, financier",
    "jeffrey epstein, convicted sex offender"
  ],
  "Donald Trump": [
    "donald trump",
    "donald j. trump",
    "donald j trump",
    "president donald trump",
    "president donald j. trump",
    "president trump",
    "former president donald trump",
    "president donald j trump",
    "the donald j. trump revocable trust",
    "trump"
  ],
  "Bill Clinton": [
    "bill clinton",
    "president bill clinton",
    "former president bill clinton",
    "president clinton",
    "william clinton",
    "william j. clinton",
    "bill clinton, former president of the united states",
    "clinton family"
  ],
  "Hillary Clinton": [
    "hillary clinton",
    "hillary rodham clinton",
    "secretary hillary clinton",
    "secretary of state hillary clinton",
    "secretary of state clinton"
  ],
  "Barack Obama": [
    "barack obama",
    "president barack obama",
    "president obama",
    "senator barack obama",
    "obama administration",
    "obama"
  ],
  "Joe Biden": ["joe biden", "joseph biden", "president biden"],
  "Bill Gates": [
    "bill gates",
    "william gates",
    "william h. gates",
    "gates",
    "bill and melinda gates foundation",
    "bill & melinda gates foundation"
  ],
  "Elon Musk": ["elon musk", "elon r. musk"],
  "Peter Thiel": ["peter thiel"],
  "Alan Dershowitz": [
    "alan dershowitz",
    "alan m. dershowitz",
    "professor alan dershowitz",
    "mr. dershowitz",
    "attorney alan dershowitz"
  ],
  "Steve Bannon": ["steve bannon", "stephen bannon", "stephen k. bannon"],
  "Ghislaine Maxwell": [
    "ghislaine maxwell",
    "ghislaine maxwell, associate of jeffrey epstein",
    "ms. maxwell"
  ],
  "Prince Andrew": ["prince andrew", "prince andrew, duke of york", "duke of york"],
  "Virginia Giuffre": ["virginia giuffre", "virginia roberts"],
  "Alan Greenspan": ["alan greenspan"],
  "Al Gore": ["al gore", "tipper gore"],
  "Alberto Gonzales": ["alberto gonzales"],
  "Alexander Acosta": ["alexander acosta", "alex acosta", "r. alexander acosta", "u.s. attorney acosta"],
  "Alfredo Rodriguez": ["alfredo rodriguez"],
  "Angela Merkel": ["angela merkel"],
  "Anwar Sadat": ["anwar sadat"],
  "Ariel Sharon": ["ariel sharon", "arik sharon"],
  "Ayatollah Ali Khamenei": ["ayatollah ali khamenei"],
  "Bashar al-Assad": ["bashar al-assad", "president bashar al-assad"],
  "Benjamin Netanyahu": ["benjamin netanyahu", "prime minister benjamin netanyahu", "bibi netanyahu", "bibi"],
  "Benjamin Harnwell": ["benjamin harnwell"],
  "Ben Bernanke": ["ben bernanke"],
  "Brett Kavanaugh": ["brett kavanaugh"],
  "Bill Richardson": ["bill richardson"],
  "Brock Pierce": ["brock pierce"],
  "Bono": ["bono"],
  "Boris Johnson": ["boris johnson"],
  "Boris Nikolic": ["boris nikolic"],
  "Bradley Edwards": ["bradley edwards", "brad edwards", "bradley j. edwards, esq."],
  "Brad Karp": ["brad karp"],
  "Brad Wechsler": ["brad wechsler"],
  "Bradley J. Edwards": ["bradley j. edwards"],
  "Charlie Rose": ["charlie rose"],
  "Chris Christie": ["chris christie"],
  "Chuck Hagel": ["chuck hagel"],
  "Condoleezza Rice": ["condoleezza rice"],
  "Dan Meridor": ["dan meridor"],
  "Dan Shomron": ["dan shomron"],
  "Danny Yatom": ["danny yatom"],
  "David Boies": ["david boies"],
  "David Cameron": ["david cameron"],
  "David Copperfield": ["david copperfield"],
  "David Koch": ["david koch"],
  "Deepak Chopra": ["deepak chopra"],
  "Deng Xiaoping": ["deng xiaoping"],
  "Dick Cheney": ["dick cheney"],
  "Dmitry Rybolovlev": ["dmitry rybolovlev"],
  "Dominique Strauss-Kahn": ["dominique strauss-kahn"],
  "Donald Rumsfeld": ["donald rumsfeld"],
  "Dwight D. Eisenhower": ["dwight d. eisenhower"],
  "Ehud Barak": ["ehud barak", "ehud barak, former prime minister of israel", "ehud"],
  "Ehud Olmert": ["ehud olmert"],
  "Eliot Spitzer": ["eliot spitzer"],
  "Elena Kagan": ["elena kagan"],
  "Emmanuel Macron": ["emmanuel macron"],
  "Eric Holder": ["eric holder"],
  "Eric Schmidt": ["eric schmidt"],
  "Francis J. Kelly": ["francis j. kelly"],
  "François Mitterrand": ["françois mitterrand", "francois mitterrand"],
  "Gary Cohn": ["gary cohn"],
  "Gerald Ford": ["gerald ford"],
  "Gerald Lefcourt": ["gerald lefcourt"],
  "George H. W. Bush": ["george h. w. bush", "george h.w. bush"],
  "George W. Bush": ["george w. bush", "president george w. bush", "george bush"],
  "George Soros": ["george soros"],
  "George Mitchell": ["george mitchell"],
  "Glenn Dubin": ["glenn dubin"],
  "Glenn Greenwald": ["glenn greenwald"],
  "Golda Meir": ["golda meir"],
  "Gordon Brown": ["gordon brown"],
  "Harvey Weinstein": ["harvey weinstein"],
  "Hillary Rodham Clinton": ["hillary rodham clinton"],
  "Hope Hicks": ["hope hicks"],
  "Hosni Mubarak": ["hosni mubarak"],
  "Ivanka Trump": ["ivanka trump"],
  "Jack Goldberger": ["jack goldberger", "mr. goldberger"],
  "Jack Scarola": ["jack scarola", "mr. scarola"],
  "James Comey": ["james comey", "fbi director james comey", "former fbi director james comey"],
  "James Patterson": ["james patterson"],
  "Jared Kushner": ["jared kushner"],
  "Jeff Bezos": ["jeff bezos"],
  "Jeff Sessions": ["jeff sessions", "attorney general jeff sessions"],
  "Jeffrey Katzenberg": ["jeffrey katzenberg"],
  "Jeffrey Sloman": ["jeffrey sloman"],
  "Jerome Powell": ["jerome powell"],
  "Jes Staley": ["jes staley"],
  "Jimmy Carter": ["jimmy carter", "president jimmy carter"],
  "Jimmy Cayne": ["jimmy cayne"],
  "Joe D. Whitley": ["joe d. whitley"],
  "John Bolton": ["john bolton"],
  "John F. Kennedy": ["john f. kennedy", "president john f. kennedy"],
  "John Kerry": ["john kerry", "secretary of state john kerry"],
  "John McCain": ["john mccain", "senator john mccain"],
  "Jordan (state)": ["king abdullah", "king hussein"],
  "Julian Assange": ["julian assange"],
  "J. Edgar Hoover": ["j. edgar hoover"],
  "Kamala Harris": ["kamala harris"],
  "Kathryn Ruemmler": ["kathryn ruemmler", "kathy ruemmler"],
  "Katie Couric": ["katie couric"],
  "Kellyanne Conway": ["kellyanne conway"],
  "Ken Starr": ["ken starr", "kenneth starr", "kenneth w. starr"],
  "Kevin Rudd": ["kevin rudd"],
  "Kevin Spacey": ["kevin spacey"],
  "Larry Gagosian": ["larry gagosian"],
  "Larry Summers": ["larry summers", "lawrence summers", "lawrence h. summers"],
  "Larry Visoski": ["larry visoski"],
  "Larry Page": ["larry page"],
  "Lawrence Krauss": ["lawrence krauss", "lawrence m. krauss"],
  "Leon Black": ["leon black"],
  "Leon Panetta": ["leon panetta"],
  "Leslie Wexner": ["leslie wexner", "les wexner"],
  "Mahmoud Abbas": ["mahmoud abbas"],
  "Mahmoud Ahmadinejad": ["mahmoud ahmadinejad"],
  "Madeleine Albright": ["madeleine albright"],
  "Marco Rubio": ["marco rubio"],
  "Martin Nowak": ["martin nowak"],
  "Mark Meadows": ["mark meadows"],
  "Mark Zuckerberg": ["mark zuckerberg"],
  "Melania Trump": ["melania trump"],
  "Michael Bloomberg": ["michael bloomberg"],
  "Michael Cohen": ["michael cohen"],
  "Michael Flynn": ["michael flynn"],
  "Michael Hayden": ["michael hayden", "general michael hayden"],
  "Michael Morell": ["michael morell"],
  "Michael Pompeo": ["michael pompeo", "mike pompeo"],
  "Michael Reiter": ["michael reiter", "chief reiter"],
  "Mick Jagger": ["mick jagger"],
  "Mick Mulvaney": ["mick mulvaney"],
  "Mike Pence": ["mike pence", "vice president mike pence"],
  "Mike Tyson": ["mike tyson"],
  "Mitt Romney": ["mitt romney"],
  "Mohamed Morsi": ["mohamed morsi"],
  "Mohammed bin Salman": ["mohammed bin salman", "mohammad bin salman", "mohammed bin salman al saud"],
  "Mort Zuckerman": ["mort zuckerman"],
  "Moshe Dayan": ["moshe dayan"],
  "Muammar Gaddafi": ["muammar gaddafi"],
  "Nancy Pelosi": ["nancy pelosi"],
  "Narendra Modi": ["narendra modi"],
  "Nathan Myhrvold": ["nathan myhrvold"],
  "Naomi Campbell": ["naomi campbell"],
  "Nicolas Sarkozy": ["nicolas sarkozy"],
  "Nigel Farage": ["nigel farage"],
  "Noam Chomsky": ["noam chomsky"],
  "Osama bin Laden": ["osama bin laden"],
  "Palm Beach Police Department": ["palm beach police department", "palm beach police"],
  "Paul Manafort": ["paul manafort"],
  "Paul Ryan": ["paul ryan"],
  "Paul Cassell": ["paul cassell"],
  "Peter Mandelson": ["peter mandelson"],
  "Prince Charles": ["prince charles"],
  "Qatar (state)": ["qatar"],
  "Rahm Emanuel": ["rahm emanuel"],
  "Ray Dalio": ["ray dalio"],
  "Recep Tayyip Erdoğan": ["recep tayyip erdoğan", "recep tayyip erdogan", "president recep tayyip erdogan"],
  "Reince Priebus": ["reince priebus"],
  "Reid Hoffman": ["reid hoffman"],
  "Rex Tillerson": ["rex tillerson"],
  "Richard Dawkins": ["richard dawkins"],
  "Richard Nixon": ["richard nixon", "president richard nixon"],
  "Ron Paul": ["ron paul"],
  "Ronald Reagan": ["ronald reagan", "president ronald reagan"],
  "Rouhani": ["iranian leadership", "iranian government"],
  "Roy Black": ["roy black"],
  "Rudy Giuliani": ["rudy giuliani"],
  "Rupert Murdoch": ["rupert murdoch"],
  "Samantha Power": ["samantha power"],
  "Sarah Ferguson": ["sarah ferguson", "duchess of york"],
  "Sarah Kellen": ["sarah kellen"],
  "Sarah Palin": ["sarah palin"],
  "Saudi royal family": ["saudi royal family", "kingdom of saudi arabia"],
  "Scott Rothstein": ["scott rothstein"],
  "Sean Spicer": ["sean spicer"],
  "Sergey Brin": ["sergey brin"],
  "Shimon Peres": ["shimon peres"],
  "Sheldon Adelson": ["sheldon adelson"],
  "Saddam Hussein": ["saddam hussein"],
  "Silvio Berlusconi": ["silvio berlusconi"],
  "Stephen Hawking": ["stephen hawking"],
  "Stephen Schwarzman": ["stephen schwarzman"],
  "Steven Hoffenberg": ["steven hoffenberg", "steven j. hoffenberg", "steven jude hoffenberg"],
  "Steven Mnuchin": ["steven mnuchin"],
  "Steve Wynn": ["steve wynn"],
  "Thomas Barrack": ["tom barrack", "thomas barrack", "thomas j. barrack jr.", "thomas j. barrack"],
  "Thomas Pritzker": ["tom pritzker", "thomas pritzker"],
  "Timothy Geithner": ["timothy geithner"],
  "Tom Barrack": ["tom barrack"],
  "Tom Menino": ["tom menino"],
  "Tony Blair": ["tony blair"],
  "Tony Kushner": ["tony kushner"],
  "Viktor Orbán": ["viktor orbán", "viktor orban"],
  "Vladimir Putin": ["vladimir putin", "president vladimir putin", "putin"],
  "Virginia Roberts": ["virginia roberts"],
  "Woody Allen": ["woody allen"],
  "Xi Jinping": ["xi jinping", "president xi jinping"],
  "Yasser Arafat": ["yasser arafat"],
  "Yitzhak Rabin": ["yitzhak rabin"],
  "Yitzhak Shamir": ["yitzhak shamir"],
  "Yossi Beilin": ["yossi beilin"],
  "Zhang": ["chinese government", "chinese communist party"],

  // Agencies/organizations and titles
  "FBI": ["fbi", "f.b.i.", "federal bureau of investigation"],
  "CIA": ["cia", "central intelligence agency"],
  "NSA": ["nsa", "national security agency"],
  "Mossad": ["mossad"],
  "Hezbollah": ["hezbollah"],
  "Hamas": ["hamas"],
  "United States": ["united states", "u.s.", "u.s. government", "us government", "u.s. congress"],
  "Russia": ["russia", "russian government"],
  "Iran": ["iran", "iranian government"],
  "Saudi Arabia": ["saudi arabia", "saudi government", "kingdom of saudi arabia"],
  "China": ["china", "chinese government", "chinese communist party"],
  "Israel": ["israel", "israeli government"],
  "United Kingdom": ["united kingdom", "uk", "buckingham palace"],
  "European Union": ["european union", "eu"],
  "European Central Bank": ["european central bank", "ecb"],
  "United Nations": ["united nations", "u.n."],
  "Department of Justice": ["u.s. department of justice", "department of justice", "justice department", "attorney general"],
  "Department of State": ["u.s. department of state", "state department", "u.s. state department"],
  "Department of Defense": ["u.s. department of defense", "defense intelligence agency", "d.o.d."],
  "Treasury Department": ["u.s. treasury department", "u.s. department of treasury", "u.s. department of treasury"],
  "Federal Reserve": ["federal reserve"],
  "U.S. Congress": ["u.s. congress", "congress", "house oversight committee"],
  "Palm Beach Police": ["palm beach police department", "palm beach police"],
  "U.S. Attorney's Office": ["u.s. attorney's office", "u.s. attorney’s office", "u.s. attorney’s office for the southern district of florida"],
  "U.S. Supreme Court": ["u.s. supreme court"],
  "U.S. Treasury": ["u.s. treasury department"],
  "U.S. Securities and Exchange Commission": ["u.s. securities and exchange commission", "sec"],
  "Harvard University": ["harvard university", "harvard"],
  "Arizona State University": ["arizona state university"],
  "Case Western Reserve University": ["case western reserve university"],
  "Booz Allen Hamilton": ["booz allen hamilton"],
  "BlackRock": ["blackrock"],
  "Goldman Sachs": ["goldman sachs"],
  "Merrill Lynch": ["merrill lynch", "bank of america merrill lynch"],
  "Deutsche Bank": ["deutsche bank"],
  "Al Rajhi Bank": ["al rajhi bank"],
  "Saudi American Bank": ["saudi american bank"],
  "Public Investment Fund": ["public investment fund"],
  "Rothschild": ["edmond de rothschild", "rothschild"],
  "International Monetary Fund": ["international monetary fund", "imf"],
  "United Arab Emirates": ["united arab emirates", "uae"],
  "Qatar": ["qatar"],
  "Biden Administration": ["biden administration"],
  "Trump Administration": ["trump administration"],
};
